<div class="pull-right">
    <a class="btn alert-info" href= "<?php echo $this->url('turma', array('action' => 'index')); ?>">Voltar</a>
</div>
<legend>
    <h3>
        <?php echo $this->escapeHtml('Cadastrar Turma'); ?>
    </h3>
</legend>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('turma', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
$turma = $form->get('turma');
echo $this->formHidden($turma->get("idTurma"));
echo $this->formHidden($turma->get("statusTurma")->setValue("A"));
?>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('nome'));
            echo $this->formInput($turma->get('nome'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('nome'));
            ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('professor'));
            echo $this->formSelect($turma->get('professor'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('professor'));
            ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('dataInicio'));
            echo $this->formInput($turma->get('dataInicio'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('dataInicio'));
            ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('dataFim'));
            echo $this->formInput($turma->get('dataFim'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('dataFim'));
            ?>
        </div>
    </div>
</div>
<?php
    echo $this->formSubmit($form->get('enviar'));
    echo $this->form()->closeTag();
?>