<div class="row">   
    <div class="panel panel-info">
        <div class="panel-heading"><h3>Turma: <b><?php echo $model->__get('nome'); ?></b></h3></div>
        <div class="panel-body">
            <label>Professor Responsável: </label> <?php echo $model->professor->__get('nome'); ?>
            <br>
            <label>Data Início: </label> <?php echo $model->__get('dataInicio')->format('d/m/Y'); ?>
            <br>
            <label>Data Fim: </label> <?php echo $model->__get('dataFim')->format('d/m/Y'); ?>
            <br>
            <label>Status: </label>
            <?php
                if ($model->__get('statusTurma') == 'A') {
                    echo "Ativo";
                } else {
                    echo "Inativo";
                }
            ?>
            <br>
            <label>Data de Criação: </label> <?php echo $model->__get('dataInsercao')->format('d/m/Y H:i:s'); ?>
            <br>
            <label>Data de Atualização: </label> <?php if ($model->__get('dataAtualizacao')) echo $model->__get('dataAtualizacao')->format('d/m/Y H:i:s'); ?>
        </div>
    </div>
</div>
<a class="btn alert-info" href="<?php echo $this->url('turma', array('action' => 'index')); ?>">Voltar</a>