
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('home'); ?>">Página inicial</a></li>
            <li class="active">Dados Pessoais</li>
        </ol>
    </div>
</div>
<div class="topo-table">
    <legend class="titulo-legenda"><?php echo $this->escapeHtml('Dados Cadastro de Novo Usuário'); ?></legend>

</div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuario/default', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);

$usuario = $form->get('usuario');
echo $this->formHidden($usuario->get('idUsuario'));
$this->formRadio()->setSeparator('</div><div class="radio">');
?>


<div class="form-group">
    <label for="inputNome">Nome Completo*:</label>
    <?php
    // renderiza html input
    echo $this->formInput($usuario->get('nome'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($usuario->get('nome'));
    ?>
</div>
<?php echo $this->formRow($usuario->get('telefoneCelular')); ?><br>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="inputusuarioTipo">Perfil Usuário:<span class="aguardando"></span></label>
            <?php
            // renderiza html input
            echo $this->formSelect($usuario->get('usuarioTipo'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($usuario->get('usuarioTipo'));
            ?>
        </div>
    </div>
    
  

    <div class="col-md-6">
        <div class="form-group">
            <label for="inputOrgaoLotaocao">Orgão de Lotação:<span class="aguardando"></span></label>
            <?php
            // renderiza html input
            echo $this->formSelect($usuario->get('orgaoLotacao'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($usuario->get('orgaoLotacao'));
            ?>
        </div>
    </div>
    
  
</div>
   

<!-- LOGIN INICIO -->
<div class="well well-sm">
    <h3>Login</h3>
</div>
<?php
$login = $usuario->get('login');
?>

    <?php echo $this->formHidden($login->get('idLogin')); ?>
 <div class="form-group">
    <label for="inputcpf">CPF*:</label>
    <?php
    // renderiza html input
    echo $this->formInput($login->get('cpf'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($login->get('cpf'));
    ?>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <label for="inputstatus">Status Usuário:<span class="aguardando"></span></label>
            <?php
            // renderiza html input
            echo $this->formSelect($login->get('status'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($login->get('status'));
            ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="inputEmail">Email:</label>
            <?php
            // renderiza html input
            echo $this->formInput($login->get('email'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($login->get('email'));
            ?>
        </div>
        
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Senha inicial Padrão: </label>
            <div class="alert alert-danger">
                                        123456                               </div>
        </div>
        
    </div>

</div>
<!-- LOGIN FIM -->


<?php
echo $this->formSubmit($form->get('enviar'));
echo $this->form()->closeTag();
echo $this->headScript()->prependFile($this->basePath() . '/js/cadastro.js');
echo $this->inlineScript()->prependFile($this->basePath('js/plugins/maskedinput/init-maskedinput.js'));
?>
