<style>
    .menu-secundario>ul.nav>li{border:1px solid #ccc;} 
</style>
<div class="row menu-secundario">   
    <ul class="nav nav-pills">
        <li role="presentation"><a href="/usuario/usuario/view">Meus Dados</a></li>
        <li role="presentation"><a href="/usuario/usuario/alterar-senha">Alterar Senha</a></li>      
    </ul>
</div>
<div class="row">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('usuario/default', array('controller' => 'usuario', 'action' => 'alterar-senha')));
    $form->prepare();
    ?>
    <?php echo $this->form()->openTag($form); ?> <br>
    <?php echo $this->formHidden($form->get('idLogin')); ?> <br>
    <div class="alert alert-danger">
        <h3>Atenção! Você está alterando sua senha.</h3>
    </div>
    <div class="form-group">
        <label for="inputSenha">Senha*:</label>
        <?php
        // renderiza html input
        echo $this->formInput($form->get('senha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<small class="text-danger">')
                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                ->setMessageCloseString('</small>')
                ->render($form->get('senha'));
        ?>
    </div>
    <div class="form-group">
        <label for="inputSenhaConf">Senha Confirmação*:</label>
        <?php
        // renderiza html input
        echo $this->formInput($form->get('senhaConfirmacao'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<small class="text-danger">')
                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                ->setMessageCloseString('</small>')
                ->render($form->get('senhaConfirmacao'));
        ?>
    </div>

    <?php echo $this->formSubmit($form->get('enviar')); ?>
    <?php echo $this->form()->closeTag(); ?>

</div>