<style>
    nav:first-child.navbar{display: none;}
    .logado-como{display: none;}
    .navegacao-preto{display: none;}
    .menu-ususario{display: none;}
    .container{ margin-top: 0px !important;}
    .rodape-geral{display: none;}


    @media print {
        nav:first-child.navbar{display: none;}
        .logado-como{display: none;}
        .navegacao-preto{display: none;}
        .menu-ususario{display: none;}
        .botoes-css{display: none;}
        .container{ margin-top: 0px !important;}
        .rodape-geral{display: none;}

        th {
            font: bold 12px sans-serif;
            border: 1px solid;

        }
        td {

            border: 1px solid;
        }
        tr {
            font: 12px sans-serif;
            border: 1px solid;
        }
        td.description {
            min-width: 200px;
            border-style: solid;
        }
        td.number {
            padding-left: 20px;
            text-align: right;
            border-style: solid;
        }  
        table{width: 100%;}  
        p.hora{
            text-align: center;
        }

    }
    legend{color: #000;}


</style>
<div class="row pull-right botoes-css" style="margin-bottom: 30px;">
    <a class="btn btn-sm btn-default" href='javascript:window.print()' target="_blank" name="print" id="print"><span class="glyphicon glyphicon-print" aria-hidden="true"></span>  Imprimir</a>

</div>
<div class="panel">
    <div class="panel-body"> 

        <table class="table table-bordered table-condensed" style="width:100%;">
            <thead>
            <td class="text-left" style="border-right:1px #fff;width: 60%;"><h3 style="padding-left: 15px;">SECRETARIA DE ESTADO E DESENOLVIMENTO, CIÊNCIA, TECNOLOGIA E ENSINO SUPERIOR.</h3></td>
            <td style="border-left:1px #fff;width: 40%;"><img src="/img/marca-site.png" class="center-block img-responsive"/></td>
            </thead>
            <tr>
                <td><b>Tipo documento: </b> <?php echo $documento->documentoTipo->documentoTipo; ?></td>              
                <td><b>Sistema: </b> <?php echo $documento->documentoTipo->sistema; ?> </td>          

            </tr>
        </table>
        <br>
        <?php echo $documento->documentoHtml; ?>    
        <legend><h3>ASSINARAM:</h3></legend>
        <table class="table table-condensed table-bordered">           
            <tbody>
                <?php foreach ($assinaturas as $assinatura) { ?>
                    <tr>
                        <td style="width: 10%">
                            <img class="img-responsive center-block" src="/img/assinatura-logo.png" />
                        </td>
                        <td>  
                            <?php
                            $cargo = '';
                            if ($assinatura->usuario->usuarioCargo->idUsuarioCargo == 1) {
                                $cargo = ', Bolsista,';
                            } else if ($assinatura->usuario->usuarioCargo->idUsuarioCargo) {
                                $cargo = 'de cargo ' . $assinatura->usuario->usuarioCargo->cargo . ', ';
                            }
                            ?>
                            <div style="padding: 10px;">
                                Documento assinado eletronicamente por <b><?php echo $assinatura->usuario->nome; ?></b> <b><?php echo $cargo ?></b> pertencente ao orgão de lotação: <b><?php echo $assinatura->usuario->orgaoLotacao->orgaoLotacao; ?></b>, 
                                em <b><?php echo $assinatura->dataInsercao->format('d/m/Y'); ?></b>, às <b><?php echo $assinatura->dataInsercao->format('H:i'); ?></b>, 
                                conforme horário oficial de Brasília, com fundamento no <a href="https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=DEC&num=47222&comp=&ano=2017" target="_blank">art. 6º, § 1º, do Decreto nº 47.222, de 26 de julho de 2017</a>.
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <table class="table table-striped">
            <tr>
                <td>
                    <img src="https://chart.googleapis.com/chart?chs=110x110&cht=qr&chl=<?php echo $_SERVER['SERVER_NAME']; ?>/application/auth/validar-documento?codVerificador=<?php echo $assinatura->documento->codVerificador; ?>"/>
                </td>
                <td>                   
                    <div style="margin-top: 30px;padding: 10px;"> A autenticidade deste documento pode ser conferida no site <a href="/application/auth/validar-documento" target="_blank">http://sead.mg.gov.br/application/auth/validar-documento</a>, 
                        informando o código verificador <b><?php echo $assinatura->documento->codVerificador; ?></b>.
                    </div>   
                </td>
            </tr>
        </table>
    </div>
</div>
<footer>        
    <div class="col-md-12 text-center" style="margin-bottom: 10px;">
        <div style="margin: 0 auto; width: 500px;">

            <?php
            setlocale(LC_TIME, 'portuguese');
            date_default_timezone_set('America/Sao_Paulo');

            $date = date('Y-m-d');
            echo '<br><br><br>Belo Horizonte, ' . date('H:i:s') . ', ' . strftime("%A, %d de %B de %Y", strtotime($date)) . '.';
            ?>

        </div>
    </div>           
</footer>