<?php
$form = $this->form;
$form->setAttribute('action', $this->urlAction);
$form->prepare();
echo $this->form()->openTag($form);

$usuario = $form->get('usuario');
echo $this->formHidden($usuario->get('idUsuario'));
$this->formRadio()->setSeparator(' ');
?>


<div class="well well-sm">
    <h3>Dados Pessoais</h3>
</div>

<div class="form-group">
    <label for="inputNome">Nome Completo*:</label>
    <?php
    // renderiza html input
    echo $this->formInput($usuario->get('nome'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($usuario->get('nome'));
    ?>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label for="inputTelefoneCelular">Telefone Celular*:</label>
            <?php
            // renderiza html input
            echo $this->formInput($usuario->get('telefoneCelular'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($usuario->get('telefoneCelular'));
            ?>
        </div>
    </div>

</div>

<?php if ($this->usuarioAutenticado()['usuario']->usuarioTipo->idUsuarioTipo == '1') { ?>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="inputusuarioTipo">Perfil Usuário:<span class="aguardando"></span></label>
                <?php
                // renderiza html input
                echo $this->formSelect($usuario->get('usuarioTipo'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($usuario->get('usuarioTipo'));
                ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="inputOrgaoLotaocao">Orgão de Lotação:<span class="aguardando"></span></label>
                <?php
                // renderiza html input
                echo $this->formSelect($usuario->get('orgaoLotacao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($usuario->get('orgaoLotacao'));
                ?>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="alert alert-danger">
                <div class="radio">
                    <b for="inputusuarioTipo">Usuário UAITEC?:   <span class="aguardando"></span></b>   
                    <?php
                    // renderiza html input
                    echo $this->formRadio($usuario->get('uaitec'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($usuario->get('uaitec'));
                    ?>
                </div>
            </div>
        </div>


    </div>
<?php } ?>  

<!-- LOGIN INICIO -->
<div class="well well-sm">
    <h3>Login</h3>
</div>
<?php
$login = $usuario->get('login');
?>

<?php echo $this->formHidden($login->get('idLogin')); ?> 
<div class="form-group">
    <label for="inputCpf">CPF*:</label>
    <input readonly="readonly"
    <?php
    // renderiza html input
    echo $this->formInput($login->get('cpf'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($login->get('cpf'));
    ?>
</div>
<?php if ($this->usuarioAutenticado()['usuario']->usuarioTipo->idUsuarioTipo == '1') { ?>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="inputstatus">Status Usuário:<span class="aguardando"></span></label>
                <?php
                // renderiza html input
                echo $this->formSelect($login->get('status'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($login->get('status'));
                ?>
            </div>
        </div>
    <?php } ?>
    <div class="col-md-4">
        <div class="form-group">
            <label for="inputEmail">Email:</label>
            <input readonly="readonly"
            <?php
            // renderiza html input
            echo $this->formInput($login->get('email'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($login->get('email'));
            ?>
        </div>

    </div>

</div>
<!-- LOGIN FIM -->




<br><br>
<a class="btn alert-info" href= "<?php echo $this->urlView ?>">Voltar</a>
<?php
echo $this->formSubmit($form->get('enviar'));
echo $this->form()->closeTag();
echo $this->headScript()->prependFile($this->basePath() . '/js/cadastro.js');
echo $this->inlineScript()->prependFile($this->basePath('js/plugins/maskedinput/init-maskedinput.js'));
?>