<style>
    .texto-registro{    
        position: relative;
        top: 10px;}
    .label-default {
        background-color: #9d9d9d;
    }
</style>

<script type="text/javascript">
    setTimeout(function () {
        location.reload(true);
    }, 7230000);
</script>
<div class="row">
    <div class="row visible-lg visible-md" > 
        <nav class="navbar navbar-static-top">
            <div class="collapse navbar-collapse">
                <ul class="menu-dois nav navbar-nav">
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>ALUNO</b>
                        </a>
                    </li>
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>TURMA</b>
                        </a>
                    </li>
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>CLIENTE</b>
                        </a>
                    </li>
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>TRIAGEM</b>
                        </a>
                    </li>
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>FEEDBACK</b>
                        </a>
                    </li>
                    <li><a href="/usuario" class="text-center">
                            <img src="img/menu/inicio.png" class="img-responsive center-block" ><br>
                            <b>CALENDÁRIO</b>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>