<style>
   .menu-secundario>ul.nav>li{border:1px solid #ccc;} 
</style>
<div class="row menu-secundario">   
    <ul class="nav nav-pills">
        <li role="presentation"><a href="/usuario/usuario/view">Meus Dados</a></li>
        <li role="presentation"><a href="/usuario/usuario/alterar-senha">Alterar Senha</a></li>      
    </ul>
</div>

<div class="row" style="margin-top: 20px;">   
    <div class="panel panel-info">

        <div class="panel-heading"><h3>USUÁRIO: <b><?php echo $model->nome; ?></b></h3></div>
        <div class="panel-body">   
            <label for="inputNome">Nome Completo: </label> <?php echo $model->nome; ?><br>
            <label for="inputNome">Cargo: </label> <?php echo $model->usuarioCargo->cargo; ?><br>
            <label for="inputNome">Orgão de Lotação: </label> <?php echo $model->orgaoLotacao->orgaoLotacao ?><br>
            <label for="inputcpf">CPF do  Usuário:</label> <?php echo $model->login->cpf; ?>           
        </div>
    </div>
</div>
