<div class="pull-right">
    <a class="btn alert-info" href= "<?php echo $this->url('matricula', array('action' => 'index')); ?>">Voltar</a>
</div>
<legend>
    <h3>
        <?php echo $this->escapeHtml('Editar Matricula'); ?>
    </h3>
</legend>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('matricula', array('action' => 'edit', 'key' => $form->get('matricula')->get("idMatricula")->getValue())));
$form->prepare();
echo $this->form()->openTag($form);
$turma = $form->get('matricula');
echo $this->formHidden($turma->get("idMatricula"));
?>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('turma'));
            echo $this->formSelect($turma->get('turma'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('turma'));
            ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
            echo $this->formLabel($turma->get('statusMatricula'));
            echo $this->formSelect($turma->get('statusMatricula'));
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($turma->get('statusMatricula'));
            ?>   
        </div>
    </div>
</div>
<?php
echo $this->formSubmit($form->get('enviar'));
echo $this->form()->closeTag();
?>