<h1><?php echo $this->escapeHtml($this->title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuarioTipo', array('action' => 'add')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?> <br>
<?php echo $this->formHidden($form->get('idUsuarioTipo')); ?> <br>
<?php echo $this->formRow($form->get('nome')); ?> <br>
<?php echo $this->formSubmit($form->get('enviar')); ?>
<?php echo $this->form()->closeTag(); ?>

<a class="btn alert-info" href= "<?php echo $this->urlView ?>">Voltar</a>