
<legend class="titulo-legenda">Nova senha</legend>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'auth', 'action' => 'alterar-acesso', 'hash' => $hash)));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?> <br>
<?php echo $this->formHidden($form->get('idLogin')); ?> <br>

<div class="form-group">
    <label for="inputSenha">Senha*:</label>
    <?php
    // renderiza html input
    echo $this->formInput($form->get('senha'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('senha'));
    ?>
</div>
<div class="form-group">
    <label for="inputSenhaConf">Senha Confirmação*:</label>
    <?php
    // renderiza html input
    echo $this->formInput($form->get('senhaConfirmacao'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('senhaConfirmacao'));
    ?>
</div>

<?php echo $this->formSubmit($form->get('enviar')); ?>
<?php echo $this->form()->closeTag(); ?>

