<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('home'); ?>">Início</a></li>
            <li class="active">Cadastrar</li>
        </ol>
    </div>
</div>
<legend class="titulo-legenda">Cadastrar</legend>
<div class="row">
  <div class="col-md-8 fale-conosco">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'auth', 'action' => 'cadastrar-login')));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?> <br>
<?php echo $this->formHidden($form->get('idLogin')); ?> <br>
<div class="form-group ">
    <label class="font-cinza label" for="inputNome">Nome<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('nome'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('nome'));
    ?>
</div>
<div class="form-group">
    <label class="font-cinza label" for="inputCpf">CPF<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('cpf'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('cpf'));
    ?>
</div>
<div class="form-group">
    <label class="font-cinza label" for="inputEmail">Email<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('email'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('email'));
    ?>
</div>
<div class="form-group">
    <label class="font-cinza label" for="inputEmailConfirmacao">Email Confirmação<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('emailConfirmacao'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('emailConfirmacao'));
    ?>
</div>
<div class="form-group">
    <label class="font-cinza label" for="inputSenha">Senha<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('senha'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('senha'));
    ?>
</div>
<div class="form-group">
    <label class="font-cinza label" for="inputSenhaConf">Senha Confirmação<span class="font-red">*</span>:</label>
    <?php
    // renderiza html input
    echo '<label>';
    echo $this->formInput($form->get('senhaConfirmacao'));
    echo '</label>';
    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($form->get('senhaConfirmacao'));
    ?>
</div>
<?php echo $this->formHidden($form->get('status')); ?> <br>
<?php echo $this->formHidden($form->get('csrf')); ?> <br>
<?php echo $this->formSubmit($form->get('enviar')); ?>
<?php echo $this->form()->closeTag(); ?>
  </div>
</div>
<?php echo $this->inlineScript()->prependFile($this->basePath('js/plugins/maskedinput/init-maskedinput.js')); ?> 