<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('home'); ?>">Início</a></li>
            <li class="active">Problemas ao se conectar?</li>
        </ol>
    </div>
</div>
<legend class="titulo-legenda">Problemas ao se conectar?</legend>
<div class="row">
    <div class="col-md-8 fale-conosco">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('application/default', array('controller' => 'auth', 'action' => 'lembrar-acesso')));
        $form->prepare();
        ?>
        <?php echo $this->form()->openTag($form); ?> <br>

        <div class="form-group">
            <label class="font-cinza label" for="inputEmail">Email<span class="font-red">*</span>:</label>
            <?php
            // renderiza html input
            echo '<label>';
            echo $this->formInput($form->get('email'));
            echo '</label>';
            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($form->get('email'));
            ?>
        </div>
        <?php echo $this->formHidden($form->get('csrf')); ?> <br>
        <?php echo $this->formSubmit($form->get('enviar')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php echo $this->inlineScript()->prependFile($this->basePath('js/plugins/maskedinput/init-maskedinput.js')); ?> 