<script src='https://www.google.com/recaptcha/api.js'></script>

<div class="row">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('application/default', array('controller' => 'auth', 'action' => 'validar-documento')));
    $form->prepare();
    ?>
    <?php echo $this->form()->openTag($form); ?>
 
    <br>
    <legend>Conferência de Autenticidade de Documentos</legend>
    <div class="col-lg-10">
        <table class="table table-condensed">
            <tbody>
                <tr>
                    <td style="width: 20%;">Código Verificador: </td>
                    <td style="width: 90%;">
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('codVerificador'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<small class="text-danger">')
                                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                                ->setMessageCloseString('</small>')
                                ->render($form->get('codVerificador'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td style="width: 20%;">Captcha: </td>
                    <td> 
                        <div class="g-recaptcha" data-sitekey="6LfnRigTAAAAAOxSGspKtAuXfn1v516ncKR_YdbW" data-callback="recaptcha_callback"></div>
                    </td>                
                </tr>
            </tbody>
        </table>   
    </div>
    <input type="hidden" id="testador" value="<?php echo $_GET['codVerificador']; ?>">
    <div class="col-lg-12">
        <div class="form-group pull-right">
             <?php echo $this->formSubmit($form->get('enviar')->setAttributes(array('disabled' => 'disabled'))); ?>       
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<div class="row" style="margin-top: 30px;">
    <?php if ($_POST) { ?>
        <?php if (!$documento == null) { ?>
            <div class="well well-sm">
                <b>HASH VALIDADORA: </b><?php echo $documento->hashAuth; ?>
            </div>
    

            <div class="col-l-12" style="margin-bottom: 10px;">
                <form id="formVerDocumento" name="formVerDocumento" action="documento" target="_blank" method="POST">
                    <input type="hidden" name="idDocumento" id="idDocumento" value="<?php echo $documento->idDocumento; ?>">
                    <button type="submit" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> Visualizar documento</button>
                </form>                
              
            </div> 

            <table class="table table-condensed table-bordered">
                <thead>
                <th>Assinante</th>
                <th>Cargo/função</th>
                <th>Orgão Lotação</th>
                <th>dataHora</th>
                </thead>
                <tbody>
                    <?php foreach ($assinaturas as $assinatura) { ?>
                        <tr>
                            <td><small><?php echo $assinatura->usuario->nome; ?></small></td>
                            <td><small><?php echo $assinatura->usuario->usuarioCargo->cargo; ?></small></td>
                            <td><small><?php echo $assinatura->usuario->orgaoLotacao->orgaoLotacao; ?></small></td>
                            <td><small><?php echo $assinatura->dataInsercao->format('d/m/Y H:i:s'); ?></small></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php echo $result->documentoHtml; ?>
        <?php } else { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-body">                    
                            <b class="text-danger">Código não encontrado</b><br>                    
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        var testador = $("#testador").val();
        $("#codVerificador").val(testador);
    });


    function recaptcha_callback() {
        $('.btn').prop("disabled", false);
    }
</script>

