<div class="row">
    <div class="col-lg-12 text-center" style="margin-top: 30px;"><div class="alert alert-danger"><h1>A página que você está procurando não existe!</h1></div></div>
    <div class="col-lg-12 text-center" style="margin-top: 30px;">
        <h3>
            Verifique se há um erro de digitação na URL ou vá para <a href="<?php echo $this->url('turma'); ?>">página inicial</a>.
        </h3>
    </div>
</div>