<?php

namespace Usuario\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Application\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idUsuario', 'usuarioTipo', 'nome', 'dataNascimento', 'email', 'telefoneFixo', 'telefoneCelular', 'senha', 'statusUsuario', 'dataInsercao', 'dataAtualizacao');
        }

        return array('__isInitialized__', 'idUsuario', 'usuarioTipo', 'nome', 'dataNascimento', 'email', 'telefoneFixo', 'telefoneCelular', 'senha', 'statusUsuario', 'dataInsercao', 'dataAtualizacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioTipo', array());

        return parent::getUsuarioTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', array());

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneFixo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneFixo', array());

        return parent::getTelefoneFixo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneCelular', array());

        return parent::getTelefoneCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusUsuario', array());

        return parent::getStatusUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInsercao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInsercao', array());

        return parent::getDataInsercao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAtualizacao', array());

        return parent::getDataAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioTipo($usuarioTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioTipo', array($usuarioTipo));

        return parent::setUsuarioTipo($usuarioTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento($dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', array($dataNascimento));

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneFixo($telefoneFixo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneFixo', array($telefoneFixo));

        return parent::setTelefoneFixo($telefoneFixo);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneCelular($telefoneCelular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneCelular', array($telefoneCelular));

        return parent::setTelefoneCelular($telefoneCelular);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusUsuario($statusUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusUsuario', array($statusUsuario));

        return parent::setStatusUsuario($statusUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInsercao($dataInsercao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInsercao', array($dataInsercao));

        return parent::setDataInsercao($dataInsercao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAtualizacao($dataAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAtualizacao', array($dataAtualizacao));

        return parent::setDataAtualizacao($dataAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

}
