<?php

namespace Usuario\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Turma extends \Application\Entity\Turma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idTurma', 'professor', 'nome', 'dataInicio', 'dataFim', 'statusTurma', 'dataInsercao', 'dataAtualizacao');
        }

        return array('__isInitialized__', 'idTurma', 'professor', 'nome', 'dataInicio', 'dataFim', 'statusTurma', 'dataInsercao', 'dataAtualizacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Turma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTurma()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTurma();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTurma', array());

        return parent::getIdTurma();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessor', array());

        return parent::getProfessor();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusTurma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusTurma', array());

        return parent::getStatusTurma();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInsercao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInsercao', array());

        return parent::getDataInsercao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAtualizacao', array());

        return parent::getDataAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTurma($idTurma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTurma', array($idTurma));

        return parent::setIdTurma($idTurma);
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessor($professor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessor', array($professor));

        return parent::setProfessor($professor);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusTurma($statusTurma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusTurma', array($statusTurma));

        return parent::setStatusTurma($statusTurma);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInsercao($dataInsercao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInsercao', array($dataInsercao));

        return parent::setDataInsercao($dataInsercao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAtualizacao($dataAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAtualizacao', array($dataAtualizacao));

        return parent::setDataAtualizacao($dataAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

}
