
<div class="topo-table">
    <h1>Perfis</h1>

</div>
<div class="corpo-table">
    <table  class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Perfil</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->perfis as $perfil) : ?>
                <tr>
                    <td><?php echo $perfil->__get('nome'); ?></td> 
                    <td>
                        <a class="btn btn-info" href="">Ver</a>
                        <a class="btn btn-warning" href="<?php echo $this->url('usuarioPerfil', array('action' => 'edit')). '/' . $perfil->__get('idUsuarioTipo')?>">Editar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

   

</div>


