<h1><?php echo $this->escapeHtml($this->title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuarioTipoTurma', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
$this->formRadio()->setSeparator('</div><div class="radio">');
$usuario = $form->get('turma');
?>
<div class="form-group">
    <label><?php echo $this->formLabel($usuario->get('usuarioTipo')); ?></label>
    <?php
    // renderiza html input
    echo $this->formSelect($usuario->get('usuarioTipo'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($usuario->get('usuarioTipo'));
    ?>
</div>

<div class="form-group">
    <label><?php echo $this->formLabel($usuario->get('nome')); ?></label>
    <?php
    // renderiza html input
    echo $this->formInput($usuario->get('nome'));

    // renderiza elemento de erro
    echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render($usuario->get('nome'));
    ?>
</div>
<?php echo $this->formElement($form->get('csrf')); ?>
<?php
//echo $this->formCollection($this->form);

echo $this->formElement($form->get('enviar'));
echo $this->form()->closeTag();
echo $this->headScript()->prependFile($this->basePath() . '/js/crud.js');
?>
<br><br>
<a class="btn alert-info" href= "<?php echo $this->urlView ?>">Voltar</a>

