
<article>

    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <?php echo $model->usuario->__get('nome'); ?><br>
        <?php echo $model->usuarioTipo->nome; ?><br>
    </p>
</article>

<a class="btn alert-info" href= "<?php echo $this->urlView ?>">Voltar</a>
                                                                                                                                                    