<div class="row">   
    <div class="panel panel-info">
        <div class="panel-heading"><h3>Produto: <b><?php echo $model->__get('nome'); ?></b></h3></div>
        <div class="panel-body">
            <label>Quantidade em estoque: </label><?php echo $model->__get('qtd');?>
            <br>
            <label>Status: </label>
            <?php
                if ($model->__get('statusProduto') == 'A') {
                    echo "Ativo";
                } else {
                    echo "Inativo";
                }
            ?>
            <br>
            <label>Data de Criação: </label> <?php echo $model->__get('dataInsercao')->format('d/m/Y H:i:s'); ?>
            <br>
            <label>Data de Atualização: </label> <?php if ($model->__get('dataAtualizacao')) echo $model->__get('dataAtualizacao')->format('d/m/Y H:i:s'); ?>
        </div>
    </div>
</div>
<a class="btn alert-info" href="<?php echo $this->url('produto', array('action' => 'index')); ?>">Voltar</a>