<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ESTEC - Estética Tecnologia ' . $this->translate(' - UNA '))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/logo-estec.png'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.icon-large.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/plugins/maskedinput/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/js/plugins/tinymce/tinymce-init.js')
                ->prependFile($this->basePath() . '/js/plugins/tinymce/tinymce.min.js')
                ->prependFile($this->basePath() . '/js/plugins/tinymce/jquery.tinymce.min.js')
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <script>
            $(document).ready(function ($) {
                //efeito de sumir a msg
                $("div#remover-auto").length == 0 || setTimeout(function () {
                    $("div#remover-auto").fadeOut(1000);
                }, 3000);
                $('#tabs').tab();
                $('.carousel').carousel();
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand link-white" href="#">
                        <img src="<?php echo $this->basePath('img/logo-estec.png') ?>" alt="ESTEC" style="width:60px; height: 30px;"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown">
                            <a href="<?php echo $this->url('usuarios', array('action' => 'index')) ?>">
                                <p style="color:#fff">Usuários</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('turma', array('action' => 'index')) ?>">
                                <p style="color:#fff">Turmas</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('matricula', array('action' => 'index')) ?>">
                                <p style="color:#fff">Matrículas</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('tipoServico', array('action' => 'index')) ?>">
                                <p style="color:#fff">Serviços</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('atendimento', array('action' => 'index')) ?>">
                                <p style="color:#fff">Atendimentos</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" >
                                <p style="color:#fff">Produtos<b class="caret"></b></p>
                            </a>
                            <ul class="dropdown-menu">
                                <li> <a href="<?php echo $this->url('produto', array('action' => 'index')) ?>">Estoque</a></li>
                                <li> <a href="<?php echo $this->url('movimentacao', array('action' => 'index')) ?>">Movimentação</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" >
                                <p style="color:#fff">Logado como: <?php echo $this->usuarioAutenticado()['usuario']->nome; ?><b class="caret"></b></p>
                            </a>
                            <ul class="dropdown-menu">
                                <li> <a href="<?php echo $this->url('usuarios', array('action' => 'meus-dados')) ?>">Meus dados</a></li>
                                <li> <a href="<?php echo $this->url('usuarios', array('action' => 'alterar-senha')) ?>">Alterar Senha</a></li>
                            </ul>
                        </li>
                        <li><a style="color: #FF0000 !important" href="<?php echo $this->url('application/auth', array('action' => 'logout')) ?>">Sair</a></li>
                    </ul> 
                </div>
            </div>
        </nav>

        <div class="container" style="margin-top: 100px;">         
            <div class="row">
                <div class="col-md-12"> 
                    <!-- Inicio Mensagem -->
                    <?php foreach ($this->flashMessages() as $namespace => $messages) : ?>
                        <?php if (count($messages)) : ?>
                            <?php foreach ($messages as $message) : ?>
                                <div id="remover-auto" class="alert alert-<?php $namespace == 'error' ? print 'danger' : print $namespace ?>">

                                    <?php
                                    if ($this->usuarioAutenticado()['usuario']->usuarioTipo->idUsuarioTipo == '1') {
                                        echo $message;
                                    }
                                    ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?> 
                    <?php echo $this->content; ?>                 
                </div>
            </div>
            <footer class="rodape-geral">        
                <div class="col-md-12 text-center">
                    <div style="margin: 0 auto; width: 500px;">© ESTEC - <?php echo date('Y') ?> | Una, Sistemas de Informação.</div>
                </div>           
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>