<div class="row">
    <table class="table table-bordered">
        <thead>
        <th>Assinante</th>
        <th>Cargo/Função</th>
        <th>Data/Hora</th>      
        <th>Documento</th>      
        </thead>
        <tbody>
            <?php foreach ($documentos as $key1 => $assinaturasDocumento) { ?>
                <tr>
                    <td><?php echo $assinaturasDocumento->usuario->nome; ?></td>
                    <td><?php echo $assinaturasDocumento->usuario->usuarioCargo->cargo; ?></td>
                    <td><?php echo $assinaturasDocumento->documento->dataInsercao->format('d/m/Y H:i:s'); ?></td>
                    <td>
                        <form id="formVerDocumento" name="formVerDocumento" action="usuario/documento" target="_blank" method="POST">
                            <input type="hidden" name="idDocumento" id="idDocumento" value="<?php echo $assinaturasDocumento->documento->idDocumento; ?>">
                            <button type="submit" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> Visualizar documento</button>
                        </form>       
                    </td>
                </tr>                
            <?php } ?>
        </tbody>
    </table>
</div>
