<h1><?php echo $this->escapeHtml($this->title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuario/default', array('action' => 'edit')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idUsuario'));
echo $this->formRow($form->get('nome'));
echo $this->formSubmit($form->get('enviar'));
echo $this->form()->closeTag();
?>
<a class="btn alert-info" href= "<?php echo $this->urlView ?>">Voltar</a>