<div class="topo-table">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>

    <a class="btn btn-success" href="<?php echo $this->placeholder('url')->add ;?>" style="margin-left: 4px;">Novo usuario</a> <!-- Criar nova categoria -->


</div>
<div class="corpo-table">
    <table  class="table table-striped table-bordered">
        <thead>
            <tr>
               
                <th>Nome</th>
                <th>Tipo</th>
                <th>Ação</th>
            </tr>

        </thead>
        <tbody>
            <?php foreach ($this->paginator as $model) : ?>
                <tr>
                   <td><?php echo $model->nome; ?></td> <!-- pegando o registro do banco -->
                   <td><?php echo $model->usuarioTipo->nome;?></td>   
                   
                    <td>
                        <a class="btn btn-info" href="<?php echo $this->placeholder('url')->view . '/' . $model->__get('idUsuario') ?>">Ver</a>
                        <a class="btn btn-warning" href="<?php echo $this->placeholder('url')->edit . '/' . $model->__get('idUsuario') ?>">Editar</a>
                        <a class="btn btn-danger" href="<?php echo $this->placeholder('url')->delete . '/' . $model->__get('idUsuario') ?>">Excluir</a>
                        
                       
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

 
<?php
    /* add at the end of the file after the table */
    echo $this->paginationControl(
            $this->paginator, 'sliding', array('partials/pagination/paginator.phtml', 'Usuario'), 
             array('controller' => 'Usuario', 'route' => 'usuario/pagina')
    );
    ?>
</div>


